/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WorkerManager_H
#define WorkerManager_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "worker_types.h"

namespace freebird {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class WorkerManagerIf {
 public:
  virtual ~WorkerManagerIf() {}

  /**
   * client calls ping method to make sure service process is active or dead
   */
  virtual void ping() = 0;
};

class WorkerManagerIfFactory {
 public:
  typedef WorkerManagerIf Handler;

  virtual ~WorkerManagerIfFactory() {}

  virtual WorkerManagerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(WorkerManagerIf* /* handler */) = 0;
};

class WorkerManagerIfSingletonFactory : virtual public WorkerManagerIfFactory {
 public:
  WorkerManagerIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<WorkerManagerIf>& iface) : iface_(iface) {}
  virtual ~WorkerManagerIfSingletonFactory() {}

  virtual WorkerManagerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(WorkerManagerIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<WorkerManagerIf> iface_;
};

class WorkerManagerNull : virtual public WorkerManagerIf {
 public:
  virtual ~WorkerManagerNull() {}
  void ping() {
    return;
  }
};


class WorkerManager_ping_args {
 public:

  WorkerManager_ping_args(const WorkerManager_ping_args&);
  WorkerManager_ping_args& operator=(const WorkerManager_ping_args&);
  WorkerManager_ping_args() {
  }

  virtual ~WorkerManager_ping_args() throw();

  bool operator == (const WorkerManager_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const WorkerManager_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WorkerManager_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WorkerManager_ping_pargs {
 public:


  virtual ~WorkerManager_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WorkerManager_ping_result {
 public:

  WorkerManager_ping_result(const WorkerManager_ping_result&);
  WorkerManager_ping_result& operator=(const WorkerManager_ping_result&);
  WorkerManager_ping_result() {
  }

  virtual ~WorkerManager_ping_result() throw();

  bool operator == (const WorkerManager_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const WorkerManager_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WorkerManager_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WorkerManager_ping_presult {
 public:


  virtual ~WorkerManager_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class WorkerManagerClient : virtual public WorkerManagerIf {
 public:
  WorkerManagerClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  WorkerManagerClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class WorkerManagerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<WorkerManagerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (WorkerManagerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  WorkerManagerProcessor(::apache::thrift::stdcxx::shared_ptr<WorkerManagerIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &WorkerManagerProcessor::process_ping;
  }

  virtual ~WorkerManagerProcessor() {}
};

class WorkerManagerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  WorkerManagerProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< WorkerManagerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< WorkerManagerIfFactory > handlerFactory_;
};

class WorkerManagerMultiface : virtual public WorkerManagerIf {
 public:
  WorkerManagerMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<WorkerManagerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~WorkerManagerMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<WorkerManagerIf> > ifaces_;
  WorkerManagerMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<WorkerManagerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class WorkerManagerConcurrentClient : virtual public WorkerManagerIf {
 public:
  WorkerManagerConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  WorkerManagerConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
