/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nydbc_constants.h"

namespace com { namespace yealink { namespace dbc { namespace idl {

const nydbcConstants g_nydbc_constants;

nydbcConstants::nydbcConstants() {
}

}}}} // namespace

